adds click [WIP]
lemonsaurus/blackbox pull request #34
Opened 2021-01-24 16:40 UTC by Inveracity

reference to #33

2021-01-24 16:40 UTC, Inveracity commented
woops, this should've been a draft PR

2021-01-25 16:21 UTC, Inveracity commented
this one is ready to be looked

2021-01-25 20:51 UTC, Inveracity commented
Apologies for all the formatting edits, VSCode seems to be quite opinionated on how to format dockerfiles and readmes

2021-01-30 09:59 UTC, lemonsaurus requested changes
Minor changes here before we merge.

2021-01-30 09:59 UTC, lemonsaurus commented on README.md
> +# TODO: decide on this naming convention
```suggestion
# Install the CLI tool
```
`blackbox-cli` will do.

2021-01-30 09:59 UTC, lemonsaurus commented on README.md
> +          restartPolicy: OnFailure
```suggestion
```

I'll add this once we've verified it working for PyDis.

2021-01-30 09:59 UTC, lemonsaurus commented on docker/Dockerfile
> +CMD ["python", "-m", "blackbox"]
```suggestion
CMD ["python", "-m", "blackbox"]
```
Maybe we actually use the `blackbox` command here, as a sanity check? Just gotta install it with pip install -e . first.

2021-01-30 10:02 UTC, lemonsaurus commented on blackbox/config.py
> +
```suggestion
```

Newline after docstring is **ILLEGAL** and ⛤⛧⛥**DEMONIC** ⛤⛧⛥

2021-01-30 10:03 UTC, lemonsaurus requested changes

2021-01-30 10:03 UTC, lemonsaurus commented on blackbox/config.py
> +        # If there is a path to the config, parse it
I'm thinking the comment on line 47 can just be above `if config_path`, where it seems to belong.

The environment get doesn't need a block comment.

2021-01-30 10:25 UTC, lemonsaurus approved these changes
one minor change more.

2021-01-30 10:25 UTC, lemonsaurus commented on blackbox/cli.py
> +                  - s3://username:password?fire=ice&magic=blue
```suggestion
                  - s3://bucket:s3.endpoint.com?aws_access_key_id=1234&aws_secret_access_key=lemondance
```

2021-01-30 10:58 UTC, merged